<a href="https://colab.research.google.com/github/duckslayer101/Basic-py-projects/blob/main/Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# ***Array***



*   Array is matrix



*   Homogenous (can only store one data type at a time)
    (There is exception also)
*   Has fixed length


*   More efficient than list
*   Have to import to use this library











In [1]:
import numpy as np

# **Linear Array**

In [2]:
a = np.array([1, 2, 3])
print(a)

# array's values are changable
a[1] = 4
print(a)

[1 2 3]
[1 4 3]


In [ ]:
# empty value/ null value/ dummy value will be in right side.

arr = np.array([1, 2, 3, 0])

# Here 0 is a dummy value.

In [3]:
# Iteration

for i in a:
  print(i)

for i in range(len(a)):
  print(a[i])

1
4
3
1
4
3


In [4]:
# Specail initilization where the values of array are treated like object

a1 = np.array([None]*5)
print(a1)

a1[2] = 3
print(a1)

# Here because of None the array is actually working as a non-homogenous since it's treating the none values as object.

[None None None None None]
[None None 3 None None]


In [5]:
# array is matrix. In this addition scenario it adds like matrix addition. It doesn't add like in list.

b = np.array([1, 2, 3])
c = np.array([4, 5, 6])

n = b+c
print(n)

[5 7 9]


In [6]:
# Resize. In order to resize an array, we need to create a new array with the new length and copy values from old array to the new array.

arr = np.array([1, 2, 3, 4])
new_arr = np.zeros(8, dtype=int)

for i in range(len(arr)):
  new_arr[i] = arr[i]
print(new_arr)

[1 2 3 4 0 0 0 0]


In [7]:
# another way of initializing

arr = np.zeros(5)
print(arr)

# Here the default data type is float. It can be changed by using dtype='....'

arr = np.zeros(5, dtype=str)
print(arr)

[0. 0. 0. 0. 0.]
['' '' '' '' '']


In [8]:
a = np.array([1, 2, 3, 4, 5])
print(a[-1::-1])

# Reverse iteration

for i in range(len(a)-1,-1,-1):
    print(a[i])

[5 4 3 2 1]
5
4
3
2
1


In [9]:
# copy in array (pass by reference)

a = np.array([1, 2, 3])
b = a
print(b)
b[1] = 4
print(a)

[1 2 3]
[1 4 3]


In [10]:
# deep copy (pass by value)

a = np.array([1, 2, 3])
b = a.copy()
print(b)
b[1] = 5
print(a)
print(b)

[1 2 3]
[1 2 3]
[1 5 3]


In [11]:
# left shift        [2 3 0]

a = np.array([1, 2, 3])
def left_shift(arr):
    for i in range(len(arr)-1):
        arr[i] = arr[i+1]
    arr[-1] = 0
    return arr

print(left_shift(a))

[2 3 0]


In [12]:
# right shift       [0 1 2]

a = np.array([1, 2, 3])
def right_shift(arr):
    for i in range(len(arr)-1, 0, -1):
        arr[i] = arr[i-1]
    arr[0] = 0
    return arr

print(right_shift(a))

[0 1 2]


In [13]:
# left rotate       [2 3 1]

a = np.array([1, 2, 3])
def left_rotate(arr):
    temp = arr[0]
    for i in range(len(arr)-1):
        arr[i] = arr[i+1]
    arr[-1] = temp
    return arr

print(left_rotate(a))

[2 3 1]


In [14]:
# right rotate      [3 1 2]

a = np.array([1, 2, 3])
def right_rotate(a):
    temp = a[-1]
    for i in range(len(a)-1, 0, -1):
        a[i] = a[i-1]
    a[0] = temp
    return a

print(right_rotate(a))

[3 1 2]


In [15]:
# Reverse (out of place)

a = np.array([1, 2, 3, 4, 5])
b = np.array([0]*len(a))
for i in range(len(b)):
    b[i] = a[len(a)-i-1]
print(b)

[5 4 3 2 1]


In [26]:
# Reverse (in place)

a = np.array([1, 2, 3, 4, 5, 6, 7])
def reverse_inplace(a1):
    for i in range(len(a1)//2):
        a1[i], a1[len(a1)-i-1] = a1[len(a1)-i-1], a1[i]
    return a1

print(reverse_inplace(a))
print(a)

[7 6 5 4 3 2 1]
[7 6 5 4 3 2 1]


In [17]:
a = 1
b = 2
a, b = b, a
print(a, b)

2 1


In [18]:
# Size of array. It's the number of non-dummy values in an array. It's used in insertion and in delation

a = np.zeros(5, dtype=int)
print(a)
a[0], a[1], a[2] = 1, 2, 3
def non_dummies(arr, size):
    for i in range(size):
        print(arr[i])

non_dummies(a, 3)
print(a)

[0 0 0 0 0]
1
2
3
[1 2 3 0 0]


In [19]:
# insert (at the end)

a = np.array([1, 2, 3, 4, 5, 6])
def resize_array(arr, new_length):
    a = np.zeros(new_length, dtype= int)
    for i in range(len(arr)):
        a[i] = arr[i]
    return a

def insert_athe_end(arr, size, value):
    if size >= len(arr):
        arr = resize_array(arr, len(arr)*2)
    arr[size] = value
    return arr


print(insert_athe_end(a, 6, 7))

[1 2 3 4 5 6 7 0 0 0 0 0]


In [20]:
a = np.array([1, 2, 3, 4])
def insertend(a, size, elem):
    if size >= len(a):
        a = resize_array(a, len(a)*2)
    a[size] = elem
    return a

print(insertend(a, 4, 5))

[1 2 3 4 5 0 0 0]


In [27]:
# insert anywhere but end

a =  np.array([1, 2, 3, 4, 5])
def insert_anywhere_butend(a, size, index, elem):
    if index<0 or index>=len(a):
        return 'Inserting is not possible'
    if size >= len(a):
        a = resize_array(a, len(a)*2)
        print(f'Resized array: {a}')
    for i in range(len(a)-1, index, -1):
        a[i] = a[i-1]
    a[index] = elem
    return a

print(insert_anywhere_butend(a, size = 5, index = 2, elem = 10))

Resized array: [1 2 3 4 5 0 0 0 0 0]
[ 1  2 10  3  4  5  0  0  0  0]


In [22]:
a = np.array([1, 2, 3, 5, 6, 0])
def insert_inbetween(arr, size, index, elem):
    if index<0 or index>=len(arr):
        return 'Not possible'
    if size >= len(arr):
        arr = resize_array(arr, len(arr)*2)
    for i in range(len(arr)-1, index, -1):
        arr[i] = arr[i-1]
    arr[index] = elem
    return arr

print(insert_inbetween(a, 5, 3, 4))

[1 2 3 4 5 6]


In [23]:
# Remove last element

arr = np.array([1, 2, 3, 4])
def rmv_last_elem(arr, size):
    if size == 0:
        return 'Remove isn\'t possible'
    arr[size-1] = 0
    return arr

print(rmv_last_elem(arr, 4))

[1 2 3 0]


In [24]:
arr = np.array([1,2,3,4,5,6,7,0,0,0])
def rmvlast(arr, size):
    if size == 0:
        return 'Not possible'
    arr[size-1] = 0
    return arr

print(rmvlast(arr, 7))

[1 2 3 4 5 6 0 0 0 0]


In [25]:
# Remove any other but last elem

def elem_inbetween(arr, size, index):
    if index<0 or index>=len(arr):
        return 'Not possible'
    arr[index] = 0
    for i in range(index, size-1):
        arr[i] = arr[i+1]
    arr[size-1] = 0
    return arr


a = np.array([1, 2, 3, 4, 5])
print(elem_inbetween(a, 5, 1))

[1 3 4 5 0]


In [30]:
def elem_remv(arr, index, size):
    if index<0 or index>=len(arr):
        return 'Not possible'
    arr[index] = 0
    for i in range(index, len(arr)-1):
        arr[i] = arr[i+1]
    arr[size-1] = 0
    return arr

arr = np.array([1, 2, 3, 4, 5])
print(elem_remv(arr, index = 2, size = 5))

[1 2 4 5 0]


In [106]:
# Sorting array
# small to big

def small_to_big(arr):
    for i in range(len(arr)-1):         # ***This (len-1) is so important***
        min = arr[i]
        for j in range(i+1, len(arr)):
            if arr[j]<min:
                min = arr[j]
                indx = j
        arr[i], arr[indx] = min, arr[i]
    return arr
arr = np.array([5, 3, 6, 8, 2, 0, -1, -2])
print(small_to_big(arr))

[-2 -1  0  2  3  5  6  8]


In [108]:
def small_to_bg(arr):
    for i in range(len(arr)-1):
        min = arr[i]
        for j in range(i+1, len(arr)):
            if arr[j]<min:
                min = arr[j]
                indx = j
        arr[i], arr[indx] = min, arr[i]
        print(arr)
    return arr

a = np.array([1, 0, 4, 2, -1, -5, 7])
print(small_to_bg(a))

[-5  0  4  2 -1  1  7]
[-5 -1  4  2  0  1  7]
[-5 -1  0  2  4  1  7]
[-5 -1  0  1  4  2  7]
[-5 -1  0  1  2  4  7]
[-5 -1  0  1  2  4  7]
[-5 -1  0  1  2  4  7]


# **Multidimensional Array**

*   2D Array
*   3D Array


*   There could be more dimensional array too


*   Dimensions have to be fixed









In [109]:
# Initialization

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [130]:
# Another way of initialization

m = np.zeros((3,2), dtype=int)      # same as linear array
print(m)

[[0 0]
 [0 0]
 [0 0]]


In [111]:
# row = length of outer array
print(f'Row: {len(arr)}')

# column = length of inner array
print(f'Column: {len(arr[0])}')


Row: 2
Column: 3


In [113]:
# another way of finding row and column

row, column = arr.shape     # This gives a tuple
print(row, column)

2 3


In [112]:
# Iteration         # row print also

arr = np.array([[1, 2, 3], [4, 5, 6]])
for i in range(len(arr)):
    for j in range(len(arr[0])):
        print(arr[i][j])

1
2
3
4
5
6


In [124]:
# column print

m = np.array([[1, 2, 3], [4, 5, 6]])
print(m)

def column_print(m):
    r, c = m.shape
    for i in range(c):
        for j in range(r):
            print(m[j][i])

column_print(m)

[[1 2 3]
 [4 5 6]]
1
4
2
5
3
6


In [125]:

m = np.array([[1, 2, 3], [4, 5, 6]])
for i in range(len(m[0])):
    for j in range(len(m)):
        print(m[j][i])

1
4
2
5
3
6


In [128]:
# Add 2 matrix

def add_matrix(m, n):
    if m.shape != n.shape:
        return 'Not possible'
    for i in range(len(m)):
        for j in range(len(m[0])):
            m[i][j] += n[i][j]
    return m

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[1,1,1], [1,1,1]])
print(add_matrix(a, b))

[[2 3 4]
 [5 6 7]]
